using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.DapperRepository.Specification.Annotations;

namespace Rochas.SqlWrapper.Test
{
    [Table("sample_array_entity")]
    public class SampleArrayEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("hash_codes")]
        public uint[] HashCodes { get; set; }

        [Filterable]
        [Column("tags")]
        public string[] Tags { get; set; }

        [Column("blob_data")]
        public byte[] BlobData { get; set; }

        [Column("active")]
        public bool Active { get; set; }
    }
}