using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.DapperRepository.Specification.Annotations;
using Rochas.DapperRepository.Specification.Enums;

namespace Rochas.SqlWrapper.Test
{
    [Table("sample_relational_entity")]
    public class SampleRelationalEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [RelationalColumn(
            TableName = "dim_entity",
            ColumnName = "entity_name",
            ColumnAlias = "EntityName",
            KeyColumn = "id",
            ForeignKeyColumn = "entity_id",
            JunctionType = RelationalJunctionType.Mandatory)]
        public string RelatedName { get; set; }

        [RelationalColumn(
            TableName = "dim_optional",
            ColumnName = "optional_name",
            ColumnAlias = "OptionalName",
            IntermediaryColumnName = "intermediary",
            KeyColumn = "id",
            ForeignKeyColumn = "optional_id",
            JunctionType = RelationalJunctionType.Optional)]
        public string OptionalRelatedName { get; set; }

        [DataAggregationColumn(ColumnName = "total_amount", AggregationType = DataAggregationType.Sum)]
        public decimal SumTotalAmount { get; set; }

        [DataAggregationColumn(ColumnName = "id", AggregationType = DataAggregationType.Count)]
        public int CountItems { get; set; }

        [DataAggregationColumn(ColumnName = "unit_price", AggregationType = DataAggregationType.Average)]
        public decimal AvgUnitPrice { get; set; }

        [DataAggregationColumn(ColumnName = "total_amount", AggregationType = DataAggregationType.Maximum)]
        public decimal MaxTotalAmount { get; set; }

        [DataAggregationColumn(ColumnName = "total_amount", AggregationType = DataAggregationType.Minimum)]
        public decimal MinTotalAmount { get; set; }
    }
}
