using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.DapperRepository.Specification.Annotations;
using Rochas.DapperRepository.Specification.Enums;

namespace Rochas.SqlWrapper.Test
{
    public class SampleNoTableEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("doc_number")]
        public long DocNumber { get; set; }

        [Filterable]
        [Column("name")]
        public string Name { get; set; }

        [Column("active")]
        public bool Active { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.OneToOne,
                       ForeignKeyAttribute = "ParentId")]
        public SampleOneForeignEntity OneToOneForeignEntity { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.ManyToOne,
                       ForeignKeyAttribute = "ChildId")]
        public SampleManyForeignEntity ManyToOneForeignEntity { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.OneToMany,
                       ForeignKeyAttribute = "ParentId")]
        public IList<SampleManyForeignEntity> OneToManyForeignEntities { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.ManyToMany,
                       IntermediaryEntity = typeof(SampleIntermedyForeignEntity),
                       IntermediaryKeyAttribute = "LeftSideId",
                       ForeignKeyAttribute = "RightSideId")]
        public IList<SampleManyForeignEntity> ManyToManyForeignEntities { get; set; }
    }
}