using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Annotations;
using Rochas.Data.Specification.Enums;

namespace Rochas.SqlWrapper.Test
{
    [Table("sample_entity")]
    public class SampleEntity
    {
        #region Public Properties

        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("child_id")]
        public int ChildId { get; set; }

        [Column("parent_id")]
        public int ParentId { get; set; }

        [Column("doc_number")]
        public long DocNumber { get; set; }

        [Column("creation_date")]
        [RangeFilter(LinkedRangeProperty = "CreationDateEnd")]
        public DateTime CreationDate { get; set; }

        [NotMapped]
        public DateTime CreationDateEnd { get; set; }

        [Filterable]
        [Column("name")]
        public string Name { get; set; }

        [Filterable]
        [Column("resume")]
        public string Resume { get; set; }

        [Column("age")]
        [RangeFilter(LinkedRangeProperty = "AgeEnd")]
        public int Age { get; set; }

        [NotMapped]
        public int AgeEnd { get; set; }

        [Column("height")]
        public decimal Height { get; set; }

        [Column("weight")]
        public decimal Weight { get; set; }

        [Column("active")]
        public bool Active { get; set; }

        #endregion

        #region Navigation Properties

        [RelatedEntity(Cardinality = RelationCardinality.OneToOne, 
                       ForeignKeyAttribute = "ParentId")]
        public SampleOneForeignEntity OneToOneForeignEntity { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.ManyToOne,
                       ForeignKeyAttribute = "ChildId")]
        public SampleManyForeignEntity ManyToOneForeignEntity { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.ManyToOne,
                       ForeignKeyAttribute = "ParentId")]
        public SampleEntity SelfReferencedEntity { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.OneToMany,
                       ForeignKeyAttribute = "ParentId")]
        public IList<SampleManyForeignEntity> OneToManyForeignEntities { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.ManyToMany,
                       IntermediaryEntity = typeof(SampleIntermedyForeignEntity),
                       IntermediaryKeyAttribute = "LeftSideId",
                       ForeignKeyAttribute = "RightSideId")]
        public IList<SampleManyForeignEntity> ManyToManyForeignEntities { get; set; }

        #endregion
    }
}