using System;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Enums;
using Rochas.Data.Specification.Annotations;
using System.ComponentModel.DataAnnotations;

namespace Rochas.SqlWrapper.Test
{
    [Table("sample_intermedy_foreign_entity")]
    public class SampleIntermedyForeignEntity
    {
        #region Public Properties

        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("left_side_id")]
        public int LeftSideId { get; set; }

        [Column("right_side_id")]
        public int RightSideId { get; set; }

        [Column("active")]
        public bool Active { get; set; }

        #endregion
    }
}