using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Annotations;
using Rochas.Data.Specification.Enums;

namespace Rochas.SqlWrapper.Test
{
    public enum SampleStatus
    {
        Pending = 1,
        Approved = 2
    }

    [Table("sample_types_entity")]
    public class SampleTypesEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("short_code")]
        public short ShortCode { get; set; }

        [Column("long_code")]
        public long LongCode { get; set; }

        [Column("float_val")]
        public float FloatVal { get; set; }

        [Column("double_val")]
        public double DoubleVal { get; set; }

        [Column("decimal_val")]
        public decimal DecimalVal { get; set; }

        [Column("guid_val")]
        public Guid GuidVal { get; set; }

        [Column("status")]
        public SampleStatus Status { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("blob")]
        public byte[] Blob { get; set; }

        [Column("codes")]
        public uint[] Codes { get; set; }
    }

    [Table("sample_listable_entity")]
    public class SampleListableEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Listable]
        [Column("name")]
        public string Name { get; set; }

        [Listable]
        [Column("description")]
        public string Description { get; set; }

        [Column("secret")]
        public string Secret { get; set; }
    }

    [Table("sample_nocol_entity")]
    public class SampleNoColKeyEntity
    {
        [Key]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("name")]
        public string Name { get; set; }
    }

    [Table("sample_range_broken_entity")]
    public class SampleRangeBrokenEntity
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("start")]
        [RangeFilter(LinkedRangeProperty = "DoesNotExist")]
        public int Start { get; set; }
    }

    [Table("sample_nokey_entity")]
    public class SampleNoKeyEntity
    {
        [Column("name")]
        public string Name { get; set; }
    }

    [Table("sample_query_entity")]
    public class SampleQueryEntity
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [RelationalColumn(TableName = "related", ColumnName = "col", ColumnAlias = "rel_col",
                          KeyColumn = "id", ForeignKeyColumn = "query_id",
                          JunctionType = RelationalJunctionType.Mandatory)]
        public string RelCol { get; set; }

        [RelationalColumn(TableName = "bridge", IntermediaryColumnName = "bridge_tab",
                          ColumnName = "bcol", KeyColumn = "id", ForeignKeyColumn = "b_id",
                          JunctionType = RelationalJunctionType.Optional)]
        public string InterRel { get; set; }

        [RelationalColumn(TableName = "left_side", ColumnName = "lcol",
                          KeyColumn = "id", ForeignKeyColumn = "l_id",
                          JunctionType = RelationalJunctionType.Optional)]
        public string LeftRel { get; set; }

        [RelationalColumn(TableName = "filter_rel", ColumnName = "fcol",
                          KeyColumn = "id", ForeignKeyColumn = "f_id",
                          JunctionType = RelationalJunctionType.Optional, Filterable = true)]
        public string FilterRel { get; set; }

        [DataAggregationColumn(ColumnName = "amount", AggregationType = DataAggregationType.Sum)]
        public decimal? SumAmount { get; set; }

        [DataAggregationColumn(ColumnName = "amount", AggregationType = DataAggregationType.Count)]
        public decimal? CountAmount { get; set; }

        [DataAggregationColumn(ColumnName = "amount", AggregationType = DataAggregationType.Average)]
        public decimal? AverageAmount { get; set; }

        [DataAggregationColumn(ColumnName = "amount", AggregationType = DataAggregationType.Minimum)]
        public decimal? MinimumAmount { get; set; }

        [DataAggregationColumn(ColumnName = "amount", AggregationType = DataAggregationType.Maximum)]
        public decimal? MaximumAmount { get; set; }
    }
}