using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.DapperRepository.Specification.Annotations;

namespace Rochas.SqlWrapper.Test
{
    [Table("sample_listable_entity")]
    public class SampleListableEntity
    {
        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Listable]
        [Column("name")]
        public string Name { get; set; }

        [Listable]
        [Column("description")]
        public string Description { get; set; }

        [Column("hidden_field")]
        public string HiddenField { get; set; }
    }
}
