using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rochas.Data.Specification.Annotations;
using Rochas.Data.Specification.Enums;

namespace Rochas.SqlWrapper.Test
{
    [Table("sample_many_foreign_entity")]
    public class SampleManyForeignEntity : SampleForeignEntity
    {
        #region Public Properties

        [Key]
        [Column("id")]
        [AutoGenerated]
        public int Id { get; set; }

        [Column("parent_id")]
        public int? ParentId { get; set; }

        [Column("creation_date")]
        public DateTime CreationDate { get; set; }

        [Column("code")]
        public int Code { get; set; }

        [Column("active")]
        public bool Active { get; set; }

        #endregion

        #region Public Navigation Properties
        
        [RelatedEntity(Cardinality = RelationCardinality.ManyToOne,
                       ForeignKeyAttribute = "ParentId")]
        public SampleEntity ParentEntity { get; set; }

        [RelatedEntity(Cardinality = RelationCardinality.ManyToMany,
                       IntermediaryEntity = typeof(SampleIntermedyForeignEntity),
                       IntermediaryKeyAttribute = "RightSideId",
                       ForeignKeyAttribute = "LeftSideId")]
        public IList<SampleEntity> ManyToManyForeignEntities { get; set; }
        
        #endregion
    }
}