using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Rochas.Data.Specification.Annotations;
using Rochas.Data.Specification.Enums;
using Rochas.SqlWrapper.Exceptions;
using Rochas.SqlWrapper.Helpers;

namespace Rochas.SqlWrapper.Test
{
    public class EntityReflectorCoverageTest
    {
        #region Column Mapping / Keys

        [Fact]
        public void GetColumnMapping_ShouldMapPropertyNamesToColumns()
        {
            var mapping = EntityReflector.GetColumnMapping(typeof(SampleEntity));

            Assert.Equal("name", mapping["Name"]);
            Assert.Equal("id", mapping["Id"]);
            Assert.Equal("creation_date", mapping["CreationDate"]);
        }

        [Fact]
        public void GetKeyColumnName_WithoutColumnAnnotation_ShouldUsePropertyName()
        {
            var props = EntityReflector.GetEntityProperties(typeof(SampleNoColKeyEntity));

            Assert.Equal("Id", EntityReflector.GetKeyColumnName(props));
        }

        [Fact]
        public void GetKeyColumnName_WithColumnAnnotation_ShouldUseColumnName()
        {
            var props = EntityReflector.GetEntityProperties(typeof(SampleEntity));

            Assert.Equal("id", EntityReflector.GetKeyColumnName(props));
        }

        [Fact]
        public void VerifyTableAnnotation_ShouldBeTrueForAnnotatedAndPlainEntities()
        {
            Assert.True(EntityReflector.VerifyTableAnnotation(typeof(SampleEntity)));
            Assert.True(EntityReflector.VerifyTableAnnotation(typeof(SampleNoTableEntity)));
        }

        #endregion

        #region Filterable / Attributes

        [Fact]
        public void IsAutoGenerated_ShouldDetectAutoGeneratedAttribute()
        {
            var generated = typeof(SampleEntity).GetProperty("Id");
            var plain = typeof(SampleEntity).GetProperty("Name");

            Assert.True(EntityReflector.IsAutoGenerated(generated));
            Assert.False(EntityReflector.IsAutoGenerated(plain));
        }

        [Fact]
        public void IsFilterableProperty_ShouldMatchByName()
        {
            Assert.True(EntityReflector.IsFilterableProperty(typeof(SampleEntity), "Name"));
            Assert.True(EntityReflector.IsFilterableProperty(typeof(SampleEntity), "resume"));
            Assert.False(EntityReflector.IsFilterableProperty(typeof(SampleEntity), "Nope"));
        }

        [Fact]
        public void GetFilterByFilterableColumns_ArrayProperty_ShouldSetLikeArray()
        {
            var entity = (SampleArrayEntity)EntityReflector.GetFilterByFilterableColumns(
                typeof(SampleArrayEntity), typeof(SampleArrayEntity).GetProperties(), "busca");

            Assert.Equal("%busca%", entity.Tags[0]);
        }

        #endregion

        #region Empty / Primary Key Helpers

        [Fact]
        public void IsEmptyObjectValue_ShouldDetectEmptyValues()
        {
            Assert.True(EntityReflector.IsEmptyObjectValue(null));
            Assert.True(EntityReflector.IsEmptyObjectValue(Guid.Empty));
            Assert.True(EntityReflector.IsEmptyObjectValue(DateTime.MinValue));
            Assert.True(EntityReflector.IsEmptyObjectValue("   "));
            Assert.True(EntityReflector.IsEmptyObjectValue("0"));
            Assert.True(EntityReflector.IsEmptyObjectValue(0));
            Assert.False(EntityReflector.IsEmptyObjectValue("123"));
            Assert.False(EntityReflector.IsEmptyObjectValue(123));
        }

        [Fact]
        public void SetFilterPrimaryKey_ShouldCopyKeyAndResetEntity()
        {
            var entity = new SampleEntity { Id = 7 };
            var props = EntityReflector.GetEntityProperties(typeof(SampleEntity));
            var filter = new SampleEntity();

            EntityReflector.SetFilterPrimaryKey(entity, props, filter);

            Assert.Equal(7, filter.Id);
            Assert.Equal(0, entity.Id);
        }

        [Fact]
        public void SetChildForeignKeyValue_ShouldPropagateParentKey()
        {
            var parent = new SampleEntity { Id = 11 };
            var child = new SampleManyForeignEntity();

            var result = EntityReflector.SetChildForeignKeyValue(
                parent, EntityReflector.GetEntityProperties(typeof(SampleEntity)),
                child, EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity)), "ParentId");

            Assert.True(result);
            Assert.Equal(11, child.ParentId);
        }

        [Fact]
        public void SetChildForeignKeyValue_EmptyParentKey_ShouldReturnFalse()
        {
            var parent = new SampleEntity();
            var child = new SampleManyForeignEntity();

            var result = EntityReflector.SetChildForeignKeyValue(
                parent, EntityReflector.GetEntityProperties(typeof(SampleEntity)),
                child, EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity)), "ParentId");

            Assert.False(result);
        }

        [Fact]
        public void SetParentForeignKeyValue_ShouldPropagateForeignKey()
        {
            var parent = new SampleEntity { ParentId = 22 };
            var child = new SampleManyForeignEntity();

            var result = EntityReflector.SetParentForeignKeyValue(
                parent, EntityReflector.GetEntityProperties(typeof(SampleEntity)),
                child, EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity)), "ParentId");

            Assert.True(result);
            Assert.Equal(22, child.Id);
        }

        [Fact]
        public void SetParentForeignKeyValue_EmptyForeignKey_ShouldReturnFalse()
        {
            var parent = new SampleEntity();
            var child = new SampleManyForeignEntity();

            var result = EntityReflector.SetParentForeignKeyValue(
                parent, EntityReflector.GetEntityProperties(typeof(SampleEntity)),
                child, EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity)), "ParentId");

            Assert.False(result);
        }

        [Fact]
        public void SetEntityForeignKey_ShouldSetChildKey()
        {
            var parent = new SampleEntity { Id = 9 };
            var child = new SampleManyForeignEntity();

            EntityReflector.SetEntityForeignKey(parent, child);

            Assert.Equal(9, child.Id);
        }

        [Fact]
        public void MatchKeys_ShouldCompareEntityKeys()
        {
            var props = typeof(SampleEntity).GetProperties();
            var a = new SampleEntity { Id = 5 };
            var b = new SampleEntity { Id = 5 };
            var c = new SampleEntity { Id = 6 };

            Assert.True(EntityReflector.MatchKeys(a, props, b));
            Assert.False(EntityReflector.MatchKeys(a, props, c));
        }

        #endregion

        #region Related Entities

        [Fact]
        public void GetRelatedEntities_ShouldReturnRelatedNavigationProperties()
        {
            var props = typeof(SampleEntity).GetProperties();
            var rels = EntityReflector.GetRelatedEntities(props).ToArray();

            Assert.Contains(rels, r => r.Name == "OneToOneForeignEntity");
            Assert.Contains(rels, r => r.Name == "OneToManyForeignEntities");
            Assert.Contains(rels, r => r.Name == "ManyToManyForeignEntities");
        }

        [Fact]
        public void GetRelatedEntities_EmptyProps_ShouldReturnEmpty()
        {
            var rels = EntityReflector.GetRelatedEntities(System.Array.Empty<System.Reflection.PropertyInfo>());

            Assert.Empty(rels);
        }

        [Fact]
        public void GetPropertiesValueList_AddAction_ShouldSkipQueryOnlyColumns()
        {
            var relation = EntityReflector.GetPropertiesValueList(
                new SampleQueryEntity(),
                typeof(SampleQueryEntity),
                EntityReflector.GetEntityProperties(typeof(SampleQueryEntity)),
                PersistenceAction.Add);

            Assert.NotNull(relation);
            Assert.Contains("TableName", relation.Keys);
        }

        [Fact]
        public void GetRelatedEntityAttribute_ShouldReturnAnnotatedAttribute()
        {
            var prop = typeof(SampleEntity).GetProperty("OneToOneForeignEntity");
            var attr = EntityReflector.GetRelatedEntityAttribute(prop);

            Assert.NotNull(attr);
            Assert.Equal(RelationCardinality.OneToOne, attr.Cardinality);
        }

        [Fact]
        public void CreateTypedList_ShouldCreateGenericListOfElementType()
        {
            var prop = typeof(SampleEntity).GetProperty("OneToManyForeignEntities");
            var list = EntityReflector.CreateTypedList(prop);

            Assert.NotNull(list);
            list.Add(new SampleManyForeignEntity());
            Assert.Single(list.Cast<object>());
        }

        #endregion

        #region Range Filter

        [Fact]
        public void GetEntityRangeFilter_LinkedPropertyMissing_ShouldThrow()
        {
            var entity = new SampleRangeBrokenEntity { Start = 5 };
            var props = EntityReflector.GetEntityProperties(typeof(SampleRangeBrokenEntity));

            Assert.Throws<Exception>(() => EntityReflector.GetEntityRangeFilter(entity, props));
        }

        #endregion

        #region Listable Attributes

        [Fact]
        public void ValidateListableAttributes_NoShowProperties_ShouldReturnAllListable()
        {
            var props = EntityReflector.GetEntityProperties(typeof(SampleListableEntity));

            EntityReflector.ValidateListableAttributes(props, null, out var exibition);

            Assert.NotNull(exibition);
            Assert.Equal(2, exibition.Length);
            Assert.Contains("Name", exibition);
            Assert.Contains("Description", exibition);
        }

        [Fact]
        public void ValidateListableAttributes_WithShowProperties_ShouldUseProvidedList()
        {
            var props = EntityReflector.GetEntityProperties(typeof(SampleListableEntity));

            EntityReflector.ValidateListableAttributes(props, "Name, Description", out var exibition);

            Assert.NotNull(exibition);
            Assert.Equal(2, exibition.Length);
        }

        [Fact]
        public void PropertyNotListableException_ShouldSetMessage()
        {
            var ex = new PropertyNotListableException("Secret");

            Assert.Contains("Secret", ex.Message);
        }

        #endregion

        #region DataTable Helpers

        [Fact]
        public void GetDataTable_ShouldBuildTableWithRows()
        {
            var list = new List<SampleEntity>
            {
                new SampleEntity { DocNumber = 1, Name = "a" },
                new SampleEntity { DocNumber = 2, Name = "b" }
            };

            var table = EntityReflector.GetDataTable(list);

            Assert.Equal(2, table.Rows.Count);
            Assert.NotNull(table.Columns["id"]);
            Assert.NotNull(table.Columns["name"]);
        }

        #endregion
    }
}