using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Linq;
using Xunit;
using Rochas.Data.Specification.Enums;
using Rochas.SqlWrapper.Exceptions;

namespace Rochas.SqlWrapper.Test
{
    public class EntityReflectorTests
    {
        #region GetColumnMapping

        [Fact]
        public void GetColumnMapping_EntityWithColumnAnnotations_ReturnsMapping()
        {
            var mapping = Helpers.EntityReflector.GetColumnMapping(typeof(SampleEntity));

            Assert.NotNull(mapping);
            Assert.Equal("id", mapping["Id"]);
            Assert.Equal("name", mapping["Name"]);
            Assert.Equal("doc_number", mapping["DocNumber"]);
        }

        [Fact]
        public void GetColumnMapping_PropertyWithoutAnnotation_UsesPropertyName()
        {
            var mapping = Helpers.EntityReflector.GetColumnMapping(typeof(SampleIntermedyForeignEntity));

            Assert.NotNull(mapping);
            Assert.Equal("left_side_id", mapping["LeftSideId"]);
        }

        #endregion

        #region GetEntityProperties

        [Fact]
        public void GetEntityProperties_Entity_ReturnsOnlyPersistableProps()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            Assert.NotNull(props);
            Assert.Contains(props, p => p.Name == "Name");
            Assert.Contains(props, p => p.Name == "Id");
        }

        [Fact]
        public void GetEntityProperties_ByteArrayProp_IsIncluded()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleArrayEntity));

            Assert.Contains(props, p => p.Name == "BlobData");
        }

        #endregion

        #region GetPropertiesValueList

        [Fact]
        public void GetPropertiesValueList_AddAction_ExcludesAutoGeneratedNonGuid()
        {
            var entity = new SampleEntity { Name = "test" };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleEntity), props, PersistenceAction.Add);

            Assert.NotNull(list);
            Assert.False(list.ContainsKey("Id"), "AutoGenerated non-Guid key should be excluded on Add");
            Assert.True(list.ContainsKey("Name"));
        }

        [Fact]
        public void GetPropertiesValueList_QueryAction_IncludesTableName()
        {
            var entity = new SampleEntity { Name = "test" };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleEntity), props, PersistenceAction.Query);

            Assert.NotNull(list);
            Assert.True(list.ContainsKey("TableName"));
            Assert.Equal("sample_entity", list["TableName"]);
        }

        [Fact]
        public void GetPropertiesValueList_QueryAction_WithRelationalAndAggregationColumns()
        {
            var entity = new SampleRelationalEntity { Name = "rel" };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleRelationalEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleRelationalEntity), props, PersistenceAction.Query);

            Assert.NotNull(list);
            Assert.True(list.ContainsKey("RelatedName"));
            Assert.True(list.ContainsKey("OptionalRelatedName"));
            Assert.True(list.ContainsKey("SumTotalAmount"));
        }

        [Fact]
        public void GetPropertiesValueList_AddAction_SkipsRelationalColumns()
        {
            var entity = new SampleRelationalEntity { Name = "rel" };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleRelationalEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleRelationalEntity), props, PersistenceAction.Add);

            Assert.NotNull(list);
            Assert.False(list.ContainsKey("RelatedName"));
        }

        #endregion

        #region ValidateListableAttributes

        [Fact]
        public void ValidateListableAttributes_WithoutShowProperties_ReturnsAllListable()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleListableEntity));

            Helpers.EntityReflector.ValidateListableAttributes(props, null, out var display);

            Assert.Equal(2, display.Length);
            Assert.Contains("Name", display);
            Assert.Contains("Description", display);
        }

        [Fact]
        public void ValidateListableAttributes_WithShowProperties_ReturnsInformedList()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleListableEntity));

            Helpers.EntityReflector.ValidateListableAttributes(props, "Name,Description", out var display);

            Assert.Equal(2, display.Length);
            Assert.Equal("Name", display[0]);
        }

        #endregion

        #region FormatSQLInputValue / value formats

        [Fact]
        public void GetPropertiesValueList_ByteArrayOnAdd_IsBase64Encoded()
        {
            var entity = new SampleArrayEntity { Name = "blob", BlobData = new byte[] { 0x01, 0x02 }, Active = true };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleArrayEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleArrayEntity), props, PersistenceAction.Add);

            Assert.NotNull(list);
            var pair = (KeyValuePair<object, object>)list["BlobData"];
            Assert.Equal("'AQI='", pair.Value);
        }

        [Fact]
        public void GetPropertiesValueList_DateTimeOnAdd_UsesCompleteFormat()
        {
            var entity = new SampleManyForeignEntity
            {
                CreationDate = new DateTime(2024, 5, 10, 14, 30, 0),
                Code = 1,
                Active = true
            };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleManyForeignEntity), props, PersistenceAction.Add);

            Assert.NotNull(list);
            var pair = (KeyValuePair<object, object>)list["CreationDate"];
            Assert.Equal("'2024-05-10 14:30:00'", pair.Value);
        }

        [Fact]
        public void GetPropertiesValueList_DateTimeOnUpdate_UsesNormalDate()
        {
            var entity = new SampleManyForeignEntity
            {
                CreationDate = new DateTime(2024, 5, 10, 14, 30, 0),
                Code = 1,
                Active = true
            };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleManyForeignEntity), props, PersistenceAction.Update);

            Assert.NotNull(list);
            var pair = (KeyValuePair<object, object>)list["CreationDate"];
            Assert.Equal("'2024-05-10'", pair.Value);
        }

        [Fact]
        public void GetPropertiesValueList_NullValue_ReturnsNullOnUpdate()
        {
            var entity = new SampleNoTableEntity { Name = null, Active = true };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleNoTableEntity));

            var list = Helpers.EntityReflector.GetPropertiesValueList(entity, typeof(SampleNoTableEntity), props, PersistenceAction.Update);

            Assert.NotNull(list);
            var pair = (KeyValuePair<object, object>)list["Name"];
            Assert.Null(pair.Value);
        }

        #endregion

        #region GetKeyColumn / IsAutoGenerated

        [Fact]
        public void GetKeyColumn_EntityWithKeyAttribute_ReturnsKeyProp()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var key = Helpers.EntityReflector.GetKeyColumn(typeof(SampleEntity), props);

            Assert.NotNull(key);
            Assert.Equal("Id", key.Name);
        }

        [Fact]
        public void GetKeyColumn_NullProps_ReturnsNull()
        {
            var key = Helpers.EntityReflector.GetKeyColumn(typeof(SampleEntity), null);

            Assert.Null(key);
        }

        [Fact]
        public void GetKeyColumn_EmptyProps_ReturnsNull()
        {
            var key = Helpers.EntityReflector.GetKeyColumn(typeof(SampleEntity), new System.Reflection.PropertyInfo[0]);

            Assert.Null(key);
        }

        [Fact]
        public void GetKeyColumnName_ReturnsColumnAnnotationName()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var name = Helpers.EntityReflector.GetKeyColumnName(props);

            Assert.Equal("id", name);
        }

        [Fact]
        public void IsAutoGenerated_KeyProp_ReturnsTrue()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var idProp = props.First(p => p.Name == "Id");

            Assert.True(Helpers.EntityReflector.IsAutoGenerated(idProp));
        }

        #endregion

        #region GetFilterByPrimaryKey / GetFilterByFilterableColumns

        [Fact]
        public void GetFilterByPrimaryKey_SetsKeyValue()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var filter = Helpers.EntityReflector.GetFilterByPrimaryKey(typeof(SampleEntity), props, 12345);

            Assert.NotNull(filter);
            var sample = Assert.IsType<SampleEntity>(filter);
            Assert.Equal(12345, sample.Id);
        }

        [Fact]
        public void GetFilterByFilterableColumns_SetsLikeValues()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var filter = Helpers.EntityReflector.GetFilterByFilterableColumns(typeof(SampleEntity), props, "roberto");

            Assert.NotNull(filter);
            var sample = Assert.IsType<SampleEntity>(filter);
            Assert.Equal("%roberto%", sample.Name);
            Assert.Equal("%roberto%", sample.Resume);
        }

        [Fact]
        public void GetFilterByFilterableColumns_WithArrayProp_SetsArrayValue()
        {
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleArrayEntity));

            var filter = Helpers.EntityReflector.GetFilterByFilterableColumns(typeof(SampleArrayEntity), props, "tag");

            Assert.NotNull(filter);
            var sample = Assert.IsType<SampleArrayEntity>(filter);
            Assert.NotNull(sample.Tags);
            Assert.Single(sample.Tags);
        }

        #endregion

        #region IsFilterableProperty

        [Fact]
        public void IsFilterableProperty_FilterableProp_ReturnsTrue()
        {
            Assert.True(Helpers.EntityReflector.IsFilterableProperty(typeof(SampleEntity), "Name"));
        }

        [Fact]
        public void IsFilterableProperty_NonFilterableProp_ReturnsFalse()
        {
            Assert.False(Helpers.EntityReflector.IsFilterableProperty(typeof(SampleEntity), "Id"));
        }

        #endregion

        #region IsEmptyObjectValue

        [Fact]
        public void IsEmptyObjectValue_Null_ReturnsTrue()
        {
            Assert.True(Helpers.EntityReflector.IsEmptyObjectValue(null));
        }

        [Fact]
        public void IsEmptyObjectValue_EmptyGuid_ReturnsTrue()
        {
            Assert.True(Helpers.EntityReflector.IsEmptyObjectValue(Guid.Empty));
        }

        [Fact]
        public void IsEmptyObjectValue_MinDateTime_ReturnsTrue()
        {
            Assert.True(Helpers.EntityReflector.IsEmptyObjectValue(DateTime.MinValue));
        }

        [Fact]
        public void IsEmptyObjectValue_NonEmptyValue_ReturnsFalse()
        {
            Assert.False(Helpers.EntityReflector.IsEmptyObjectValue("value"));
        }

        [Fact]
        public void IsEmptyObjectValue_ZeroNumeric_ReturnsTrue()
        {
            Assert.True(Helpers.EntityReflector.IsEmptyObjectValue(0));
        }

        #endregion

        #region SetFilterPrimaryKey / FK setters

        [Fact]
        public void SetFilterPrimaryKey_MovesKeyToFilterEntity()
        {
            var entity = new SampleEntity { Id = 99 };
            var filter = new SampleEntity();
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            Helpers.EntityReflector.SetFilterPrimaryKey(entity, props, filter);

            Assert.Equal(99, filter.Id);
            Assert.Equal(0, entity.Id);
        }

        [Fact]
        public void SetChildForeignKeyValue_WithParentKey_SetsChildForeignKey()
        {
            var parent = new SampleEntity { Id = 7 };
            var child = new SampleManyForeignEntity();
            var parentProps = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));
            var childProps = Helpers.EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity));

            var result = Helpers.EntityReflector.SetChildForeignKeyValue(parent, parentProps, child, childProps, "ParentId");

            Assert.True(result);
            Assert.Equal(7, child.ParentId);
        }

        [Fact]
        public void SetChildForeignKeyValue_WithoutParentKey_ReturnsFalse()
        {
            var parent = new SampleEntity { Id = 0 };
            var child = new SampleManyForeignEntity();
            var parentProps = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));
            var childProps = Helpers.EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity));

            var result = Helpers.EntityReflector.SetChildForeignKeyValue(parent, parentProps, child, childProps, "ParentId");

            Assert.False(result);
        }

        [Fact]
        public void SetParentForeignKeyValue_WithForeignKey_SetsChildKey()
        {
            var parent = new SampleEntity { ParentId = 11 };
            var child = new SampleManyForeignEntity();
            var parentProps = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));
            var childProps = Helpers.EntityReflector.GetEntityProperties(typeof(SampleManyForeignEntity));

            var result = Helpers.EntityReflector.SetParentForeignKeyValue(parent, parentProps, child, childProps, "ParentId");

            Assert.True(result);
            Assert.Equal(11, child.Id);
        }

        [Fact]
        public void SetEntityForeignKey_CopiesParentKeyToChildKey()
        {
            var parent = new SampleEntity { Id = 25 };
            var child = new SampleManyForeignEntity();

            Helpers.EntityReflector.SetEntityForeignKey(parent, child);

            Assert.Equal(25, child.Id);
        }

        [Fact]
        public void MatchKeys_EqualKeys_ReturnsTrue()
        {
            var entity1 = new SampleEntity { Id = 5 };
            var entity2 = new SampleEntity { Id = 5 };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            Assert.True(Helpers.EntityReflector.MatchKeys(entity1, props, entity2));
        }

        [Fact]
        public void MatchKeys_DifferentKeys_ReturnsFalse()
        {
            var entity1 = new SampleEntity { Id = 5 };
            var entity2 = new SampleEntity { Id = 6 };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            Assert.False(Helpers.EntityReflector.MatchKeys(entity1, props, entity2));
        }

        #endregion

        #region GetRelatedEntities / CreateTypedList

        [Fact]
        public void GetRelatedEntities_EntityWithRelatedProps_ReturnsThem()
        {
            var props = typeof(SampleEntity).GetProperties();

            var related = Helpers.EntityReflector.GetRelatedEntities(props);

            Assert.NotEmpty(related);
            Assert.Contains(related, p => p.Name == "OneToOneForeignEntity");
        }

        [Fact]
        public void GetRelatedEntities_NullProps_ReturnsEmpty()
        {
            var related = Helpers.EntityReflector.GetRelatedEntities(null);

            Assert.Empty(related);
        }

        [Fact]
        public void GetRelatedEntityAttribute_ReturnsAttribute()
        {
            var prop = typeof(SampleEntity).GetProperty("OneToOneForeignEntity");

            var attr = Helpers.EntityReflector.GetRelatedEntityAttribute(prop);

            Assert.NotNull(attr);
        }

        [Fact]
        public void CreateTypedList_CreatesListOfElementType()
        {
            var prop = typeof(SampleEntity).GetProperty("OneToManyForeignEntities");

            var list = Helpers.EntityReflector.CreateTypedList(prop);

            Assert.NotNull(list);
            Assert.IsAssignableFrom<IList<SampleManyForeignEntity>>(list);
        }

        #endregion

        #region GetEntityRangeFilter

        [Fact]
        public void GetEntityRangeFilter_WithLinkedProps_ReturnsRanges()
        {
            var entity = new SampleEntity { Age = 18, AgeEnd = 65 };
            var props = Helpers.EntityReflector.GetEntityProperties(typeof(SampleEntity));

            var ranges = Helpers.EntityReflector.GetEntityRangeFilter(entity, props);

            Assert.NotNull(ranges);
            Assert.True(ranges.ContainsKey("age"));
            Assert.Equal(new object[] { 18, 65 }, ranges["age"]);
        }

        #endregion

        #region VerifyTableAnnotation / GetDataTable

        [Fact]
        public void VerifyTableAnnotation_WithTableAttribute_ReturnsTrue()
        {
            Assert.True(Helpers.EntityReflector.VerifyTableAnnotation(typeof(SampleEntity)));
        }

        [Fact]
        public void VerifyTableAnnotation_WithoutTableAttribute_ReturnsTrue()
        {
            Assert.True(Helpers.EntityReflector.VerifyTableAnnotation(typeof(SampleNoTableEntity)));
        }

        [Fact]
        public void GetDataTable_Collection_ReturnsTableWithRows()
        {
            var items = new List<SampleNoTableEntity>
            {
                new SampleNoTableEntity { Id = 1, Name = "a" },
                new SampleNoTableEntity { Id = 2, Name = "b" }
            };

            var table = Helpers.EntityReflector.GetDataTable(items);

            Assert.NotNull(table);
            Assert.Equal(2, table.Rows.Count);
            Assert.True(table.Columns.Contains("Name"));
        }

        #endregion

        #region PropertyNotListableException

        [Fact]
        public void PropertyNotListableException_Constructor_SetsMessage()
        {
            var ex = new PropertyNotListableException("Name");

            Assert.Contains("Name", ex.Message);
            Assert.Contains("listable", ex.Message, StringComparison.OrdinalIgnoreCase);
        }

        #endregion
    }
}
