using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;
using System.Data;
using System.Collections;
using System.Globalization;
using Rochas.Data.Specification.Annotations;
using Rochas.Data.Specification.Enums;
using Rochas.SqlWrapper.Exceptions;
using Rochas.SqlWrapper.Helpers.SQL;

namespace Rochas.SqlWrapper.Helpers
{
    public static class EntityReflector
    {
        // ── Caches de reflexão (estáticos, thread-safe) ──────────────────────
        // Tipos de entidade são imutáveis em runtime → cache seguro.
        // Evitam GetCustomAttribute/GetCustomAttributes a cada chamada.

        private static readonly ConcurrentDictionary<Type, string> TableNames = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo> KeyColumns = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo[]> FilterablePropsCache = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo[]> RelatedEntityPropsCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, bool> IsRelatedEntityCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, bool> IsAutoGeneratedCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, bool> IsNotMappedCache = new();
        private static readonly ConcurrentDictionary<PropertyInfo, ColumnAttribute> ColumnAnnotations = new();
        private static readonly ConcurrentDictionary<PropertyInfo, RelatedEntityAttribute> RelatedEntityAttributes = new();
        private static readonly ConcurrentDictionary<Type, Dictionary<string, string>> ColumnMappingCache = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo[]> EntityPropsCache = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo[]> TypePropsCache = new();
        private static readonly ConcurrentDictionary<Type, PropertyInfo[]> ClassChildPropsCache = new();
        private static readonly ConcurrentDictionary<Type, Func<object, object>> TypeValueConvertersCache = new();

        /// <summary>
        /// Retorna mapeamentoPropertyName → columnName cacheado por tipo de entidade.
        /// Não inclui valores — apenas nomes das colunas.
        /// </summary>
        public static Dictionary<string, string> GetColumnMapping(Type entityType, DatabaseEngine? engine = null)
        {
            return ColumnMappingCache.GetOrAdd(entityType, t =>
            {
                var mapping = new Dictionary<string, string>();
                var props = GetEntityProperties(t);

                foreach (var prop in props)
                {
                    var isNotMapped = IsNotMappedCache.GetOrAdd(prop, p =>
                        p.GetCustomAttributes().Any(atb => atb is NotMappedAttribute));

                    if (isNotMapped) continue;

                    var columnAnnotation = ColumnAnnotations.GetOrAdd(prop, p =>
                        p.GetCustomAttribute(typeof(ColumnAttribute)) as ColumnAttribute);

                    var columnName = columnAnnotation?.Name ?? prop.Name;

                    mapping[prop.Name] = columnName;
                }

                return mapping;
            });
        }

        /// <summary>
        /// Retorna array de PropertyInfo filtrado por tipo de entidade (cacheado).
        /// Exclui propriedades de classe do mesmo namespace, collections complexas e
        /// arrays de bytes (blob). Permite arrays 1-D de primitivos (uint[], int[],
        /// string[] etc.), persistidos como CSV em coluna TEXT.
        /// </summary>
        public static PropertyInfo[] GetEntityProperties(Type entityType)
        {
            return EntityPropsCache.GetOrAdd(entityType, t =>
            {
                var nameSpacePrefix = t.Namespace.Substring(0, t.Namespace.IndexOf("."));

                return t.GetProperties()
                    .Where(p => !(p.PropertyType.IsClass && p.PropertyType.Namespace?.StartsWith(nameSpacePrefix) == true))
                    .Where(p => p.PropertyType == typeof(string)
                                || !typeof(System.Collections.IEnumerable).IsAssignableFrom(p.PropertyType)
                                || IsPersistableArray(p.PropertyType))
                    .ToArray();
            });
        }

        /// <summary>
        /// Indica se o tipo é um array 1-D persistível em coluna TEXT.
        /// Primitivos (uint[], int[], string[]...) viram CSV; byte[] vira base64.
        /// Exclui byte[][] e arrays multidimensionais (estruturas complexas).
        /// </summary>
        private static bool IsPersistableArray(Type type)
        {
            if (!type.IsArray || type.GetArrayRank() != 1) return false;
            if (type == typeof(byte[][])) return false;

            var elementType = type.GetElementType();
            return elementType == typeof(byte)
                || elementType == typeof(string)
                || elementType == typeof(decimal)
                || (elementType.IsPrimitive && elementType != typeof(char));
        }

        public static Dictionary<object, object> GetPropertiesValueList(object entity, Type entityType, PropertyInfo[] entityProperties, PersistenceAction action, DatabaseEngine? engine = null)
        {
            var objectSQLDataRelation = new Dictionary<object, object>();

            var tableName = GetTableName(entityType, engine);
            if (!string.IsNullOrWhiteSpace(tableName))
                objectSQLDataRelation.Add("TableName", tableName);

            foreach (var prop in entityProperties)
            {
                var isRelated = IsRelatedEntityCache.GetOrAdd(prop, p =>
                    p.GetCustomAttributes().Any(atb => atb is RelatedEntityAttribute));

                if (!isRelated)
                {
                    var isAutoGenerated = IsAutoGeneratedCache.GetOrAdd(prop, p =>
                        p.GetCustomAttributes().Any(atb => atb is AutoGeneratedAttribute));

                    var isNotMapped = IsNotMappedCache.GetOrAdd(prop, p =>
                        p.GetCustomAttributes().Any(atb => atb is NotMappedAttribute));

                    var isArrayType = prop.PropertyType == typeof(byte[][]);

                    var relationalAnnotation = prop.GetCustomAttribute(typeof(RelationalColumn)) as RelationalColumn;
                    var aggregationAnnotation = prop.GetCustomAttribute(typeof(DataAggregationColumn)) as DataAggregationColumn;

                    var isQueryOnly = relationalAnnotation != null || aggregationAnnotation != null;

                    if (isQueryOnly && action != PersistenceAction.Query && action != PersistenceAction.Get)
                        continue;

                    object columnKey;
                    if (relationalAnnotation != null)
                    {
                        columnKey = relationalAnnotation;
                    }
                    else if (aggregationAnnotation != null)
                    {
                        columnKey = aggregationAnnotation;
                    }
                    else
                    {
                        var columnAnnotation = ColumnAnnotations.GetOrAdd(prop, p =>
                            p.GetCustomAttribute(typeof(ColumnAttribute)) as ColumnAttribute);
                        columnKey = columnAnnotation?.Name ?? prop.Name;
                    }

                    var columnValue = prop.GetValue(Convert.ChangeType(entity, entity.GetType()), null);
                    columnValue = FormatSQLInputValue(prop, columnValue, action);

                    if (!((action == PersistenceAction.Add) && isAutoGenerated && prop.PropertyType != typeof(Guid)) && !isNotMapped && !isArrayType)
                    {
                        var sqlValueColumn = new KeyValuePair<object, object>(columnKey, columnValue);
                        objectSQLDataRelation.Add(prop.Name, sqlValueColumn);
                    }
                }
            }

            return objectSQLDataRelation;
        }

        public static void ValidateListableAttributes(PropertyInfo[] entityProps, string showProperties, out string[] exibitionAttributes)
        {
            IEnumerable<PropertyInfo> listableAttributes = null;
            bool notListableAttribute = false;

            listableAttributes = entityProps.Where(prp => prp.GetCustomAttributes(true).
                                             Where(ca => (ca is ListableAttribute)).Any());

            if (string.IsNullOrWhiteSpace(showProperties))
            {
                exibitionAttributes = new string[listableAttributes.Count()];

                int cont = 0;
                foreach (var listableAttrib in listableAttributes)
                {
                    exibitionAttributes[cont] = listableAttrib.Name;
                    cont++;
                }
            }
            else
            {
                exibitionAttributes = showProperties.Split(',');

                foreach (var attrib in exibitionAttributes)
                {
                    notListableAttribute = !listableAttributes.Contains(attrib.GetType().GetProperty(attrib));
                    if (!notListableAttribute) throw new PropertyNotListableException(attrib); break;
                }
            }
        }

        private static string GetTableName(Type entityType, DatabaseEngine? engine = null)
        {
            var name = TableNames.GetOrAdd(entityType, t =>
            {
                var attr = t.GetCustomAttribute(typeof(TableAttribute)) as TableAttribute;
                if (attr == null) return t.Name;
                return string.IsNullOrWhiteSpace(attr.Schema)
                    ? attr.Name
                    : $"{attr.Schema}.{attr.Name}";
            });

            return name;
        }

        private static object FormatSQLInputValue(PropertyInfo column, object columnValue, PersistenceAction action)
        {
            if (columnValue != null)
            {
                var isRequired = column.GetCustomAttributes().Any(atb => atb is RequiredAttribute);

                // byte[] é persistido como base64 em coluna TEXT (bancos sem blob nativo
                // em campos mapeados pela ORM). byte[][] é pulado em GetPropertiesValueList
                // e nunca chega aqui.
                if (columnValue is byte[] byteArray)
                {
                    if (action == PersistenceAction.Add || action == PersistenceAction.Update)
                    {
                        columnValue = string.Concat("'", Convert.ToBase64String(byteArray), "'");
                        return columnValue;
                    }

                    return columnValue;
                }

                // Arrays 1-D de primitivos (uint[], int[], string[]...) são persistidos
                // como CSV em coluna TEXT ("1,2,3"). Na persistência o valor vira texto
                // CSV; em filtros (Query/Get/Count) o array cru permanece para
                // SetFilterSqlParameters ignorá-lo no WHERE.
                if (columnValue.GetType().IsArray && columnValue.GetType().GetArrayRank() == 1)
                {
                    var elementType = columnValue.GetType().GetElementType();
                    if (elementType != typeof(byte)
                        && (action == PersistenceAction.Add || action == PersistenceAction.Update))
                    {
                        var csv = string.Join(",", ((IEnumerable)columnValue)
                            .Cast<object>()
                            .Select(v => Convert.ToString(v, CultureInfo.InvariantCulture)));
                        columnValue = string.Concat("'", csv.Replace("'", "\""), "'");
                        return columnValue;
                    }

                    return columnValue;
                }

                switch (columnValue.GetType().ToString())
                {
                    case SQL.DataType.Short:
                        if (((short)columnValue == short.MinValue) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        break;
                    case SQL.DataType.Integer:
                        break;
                    case SQL.DataType.Long:
                        if (((long)columnValue == long.MinValue) && !isRequired)
                            columnValue = SqlDefaultValue.Null;
                        break;
                    case SQL.DataType.Boolean:
                        break;
                    case SQL.DataType.String:
                        var strValue = columnValue.ToString().Replace("'", "\"");
                        if (strValue != null)
                            columnValue = string.Concat("'", strValue, "'");
                        else
                            columnValue = SqlDefaultValue.Null;

                        break;
                    case SQL.DataType.DateTime:
                        if (!(((DateTime)columnValue).Equals(DateTime.MinValue)))
                        {
                            var dateFormat = (action == PersistenceAction.Add) ?
                                              DateTimeFormat.CompleteDateTime :
                                              DateTimeFormat.NormalDate;

                            columnValue = "'" + ((DateTime)columnValue).ToString(dateFormat) + "'";
                        }
                        else
                            columnValue = SqlDefaultValue.Null;
                        break;
                    case SQL.DataType.Float:
                    case SQL.DataType.Double:
                    case SQL.DataType.Decimal:
                        columnValue = columnValue.ToString().Replace(",", ".");
                        break;
                    case SQL.DataType.Guid:
                        if (((Guid)columnValue == Guid.Empty) && action != PersistenceAction.Add)
                            columnValue = SqlDefaultValue.Null;
                        else
                            columnValue = string.Concat("'", columnValue.ToString(), "'");
                        break;
                }

                if (columnValue.GetType().IsEnum)
                    columnValue = Convert.ToInt32(columnValue);
        }
            else
            {
                columnValue = (action == PersistenceAction.Add) ? SqlDefaultValue.Null : null;
            }

            return columnValue;
        }

        public static PropertyInfo GetKeyColumn(Type entityType, PropertyInfo[] entityProps)
        {
            if (entityProps == null || entityProps.Length == 0) return null;

            return KeyColumns.GetOrAdd(entityType, t =>
                entityProps.FirstOrDefault(prp => prp.GetCustomAttributes().Any(atb => atb is KeyAttribute)));
        }

        public static PropertyInfo GetKeyColumn(PropertyInfo[] entityProps)
        {
            if (entityProps == null || entityProps.Length == 0) return null;

            var entityType = entityProps[0].DeclaringType;
            return GetKeyColumn(entityType, entityProps);
        }

        public static bool IsAutoGenerated(PropertyInfo prop)
        {
            return IsAutoGeneratedCache.GetOrAdd(prop, p =>
                p.GetCustomAttributes().Any(atb => atb is AutoGeneratedAttribute));
        }

        public static object GetFilterByPrimaryKey(Type entityType, PropertyInfo[] entityProps, object key)
        {
            var entity = Activator.CreateInstance(entityType);
            if (entity != null)
            {
                var keyColumn = GetKeyColumn(entityProps);
                keyColumn?.SetValue(entity, key);
            }

            return entity;
        }

        public static object GetFilterByFilterableColumns(Type entityType, PropertyInfo[] entityProps, object criteria)
        {
            var entity = Activator.CreateInstance(entityType);
            if (entity != null)
            {
                var filterableProps = FilterablePropsCache.GetOrAdd(entityType, t =>
                    entityProps.Where(prp => prp.GetCustomAttribute(typeof(FilterableAttribute)) != null).ToArray());

                var likeValue = "%" + criteria + "%";
                foreach (var prop in filterableProps)
                {
                    if (prop.PropertyType.IsArray && prop.PropertyType != typeof(byte[]))
                    {
                        var arr = Array.CreateInstance(prop.PropertyType.GetElementType(), 1);
                        arr.SetValue(likeValue, 0);
                        prop.SetValue(entity, arr);
                    }
                    else
                        prop.SetValue(entity, likeValue);
                }
            }

            return entity;
        }

        public static bool IsFilterableProperty(Type entityType, string propertyName)
        {
            var filterableProps = FilterablePropsCache.GetOrAdd(entityType, t =>
            {
                var props = entityType.GetProperties();
                return props.Where(prp => prp.GetCustomAttribute(typeof(FilterableAttribute)) != null).ToArray();
            });

            return filterableProps.Any(p => p.Name.Equals(propertyName, StringComparison.OrdinalIgnoreCase));
        }

        public static bool IsEmptyObjectValue(object value)
        {
            if (value == null) return true;
            if (value is Guid guid && guid == Guid.Empty) return true;
            if (value is DateTime dt && dt == DateTime.MinValue) return true;
            var strVal = value.ToString().Trim();
			return string.IsNullOrWhiteSpace(strVal)
                || (double.TryParse(strVal, out double fake) && (fake == 0));
		}

        public static void SetFilterPrimaryKey(object entity, PropertyInfo[] entityProps, object filterEntity)
        {
            var entityKeyColumn = GetKeyColumn(entityProps);

            if (entityKeyColumn != null)
            {
                var keyValue = entityKeyColumn.GetValue(entity, null);
                entityKeyColumn.SetValue(filterEntity, keyValue, null);
                entityKeyColumn.SetValue(entity, 0, null);
            }
        }

        public static bool SetChildForeignKeyValue(object parentEntity, PropertyInfo[] parentProps, object childEntity,
                                                   PropertyInfo[] childProps, string foreignKeyPropName)
        {
            bool result = false;

            var parentKey = GetKeyColumn(parentProps);
            var childForeignKey = childProps?.FirstOrDefault(prp => prp.Name.Equals(foreignKeyPropName));

            if ((parentKey != null) && (childForeignKey != null))
            {
                var parentKeyValue = parentKey.GetValue(parentEntity, null);
				if (!IsEmptyObjectValue(parentKeyValue))
				{
					childForeignKey.SetValue(childEntity, parentKeyValue, null);
					result = true;
				}
			}

            return result;
        }

        public static bool SetParentForeignKeyValue(object parentEntity, PropertyInfo[] parentProps, object childEntity,
                                                    PropertyInfo[] childProps, string foreignKeyPropName)
        {
            bool result = false;

            var parentForeignKey = parentProps?.FirstOrDefault(prp => prp.Name.Equals(foreignKeyPropName));
            var childKey = GetKeyColumn(childProps);

            if ((parentForeignKey != null) && (childKey != null))
            {
                var foreignKeyValue = parentForeignKey.GetValue(parentEntity, null);
				if (!IsEmptyObjectValue(foreignKeyValue))
                {
					childKey.SetValue(childEntity, foreignKeyValue, null);
					result = true;
				}
			}

            return result;
        }

        public static IEnumerable<PropertyInfo> GetRelatedEntities(PropertyInfo[] entityProperties)
        {
            if (entityProperties == null || entityProperties.Length == 0)
                return Enumerable.Empty<PropertyInfo>();

            var entityType = entityProperties[0].DeclaringType;
            return RelatedEntityPropsCache.GetOrAdd(entityType, t =>
                entityProperties.Where(prp => prp.GetCustomAttributes(true)
                                    .Any(atb => atb.GetType().Name.Equals("RelatedEntityAttribute"))).ToArray());
        }

        public static RelatedEntityAttribute GetRelatedEntityAttribute(PropertyInfo relatedEntity)
        {
            return RelatedEntityAttributes.GetOrAdd(relatedEntity, p =>
                p.GetCustomAttributes(true)
                 .FirstOrDefault(atb => atb.GetType().Name.Equals("RelatedEntityAttribute")) as RelatedEntityAttribute);
        }

        public static bool MatchKeys(object sourceEntity, PropertyInfo[] entityProps, object destinEntity)
        {
            var entityKey = GetKeyColumn(entityProps);

            return entityKey.GetValue(sourceEntity, null)
                   .Equals(entityKey.GetValue(destinEntity, null));
        }

        public static void SetEntityForeignKey(object parentEntity, object childEntity)
        {
            var parentProps = parentEntity.GetType().GetProperties();
            var parentKey = GetKeyColumn(parentProps);

            var childProps = childEntity.GetType().GetProperties();
            var childForeignKey = GetKeyColumn(childProps);

            if ((parentKey != null) && (childForeignKey != null))
                childForeignKey.SetValue(childEntity, parentKey.GetValue(parentEntity, null), null);
        }

        public static string GetKeyColumnName(PropertyInfo[] entityProps)
        {
            var result = string.Empty;
            var keyProperty = GetKeyColumn(entityProps);
            if (keyProperty != null)
            {
                var columnAnnotation = ColumnAnnotations.GetOrAdd(keyProperty, p =>
                    p.GetCustomAttribute(typeof(ColumnAttribute)) as ColumnAttribute);

                if (columnAnnotation != null)
                    result = columnAnnotation.Name;
                else
                    result = keyProperty.Name;
            }

            return result;
        }

        public static Dictionary<string, object[]> GetEntityRangeFilter(object entity, PropertyInfo[] entityProps)
        {
            Dictionary<string, object[]> result = null;

            var rangeFilterProps =  entityProps.Where(prp => prp.GetCustomAttributes(true)
                                                 .Any(atb => atb.GetType().Name.Equals("RangeFilterAttribute")
                                                      && !string.IsNullOrWhiteSpace(((RangeFilterAttribute)atb).LinkedRangeProperty)));

            if (rangeFilterProps != null)
            {
                result = new Dictionary<string, object[]>();
                foreach (var prop in rangeFilterProps)
                {
                    var columnAnnotation = ColumnAnnotations.GetOrAdd(prop, p =>
                        p.GetCustomAttribute(typeof(ColumnAttribute)) as ColumnAttribute);

                    var columnName = columnAnnotation?.Name ?? prop.Name;

                    var rangePropAttrib = prop.GetCustomAttributes(true)
                                              .FirstOrDefault(lkp => lkp.GetType().Name.Equals("RangeFilterAttribute"));

                    var linkedRangePropName = ((RangeFilterAttribute)rangePropAttrib).LinkedRangeProperty;
                    var lkdRangeProp = entityProps.FirstOrDefault(lkp => lkp.Name.Equals(linkedRangePropName));
                    if (lkdRangeProp != null)
                    {
                        result.Add(columnName,
                            new object[] { prop.GetValue(entity), lkdRangeProp.GetValue(entity) });
                    }
                    else
                        throw new Exception("Linked range property not found.");
                }
            }

            return result;
        }

        public static IList CreateTypedList(PropertyInfo child)
        {
            var childListType = child.PropertyType.GetGenericArguments()[0];
            var dynamicManyType = typeof(List<>).MakeGenericType(new Type[] { childListType });
            return (IList)Activator.CreateInstance(dynamicManyType, true);
        }

        public static bool VerifyTableAnnotation(Type entityType)
        {
            var tableName = GetTableName(entityType);
            return !string.IsNullOrWhiteSpace(tableName);
        }

        public static DataTable GetDataTable<T>(ICollection<T> list)
        {
            DataTable table = CreateTable<T>();
            var properties = typeof(T).GetProperties();
            foreach (var item in list)
            {
                DataRow row = table.NewRow();
                foreach (var prop in properties)
                {
                    row[prop.Name] = prop.GetValue(item);
                }
                table.Rows.Add(row);
            }
            return table;
        }
        private static DataTable CreateTable<T>()
        {
            Type entityType = typeof(T);
            DataTable table = new DataTable(entityType.Name);
            var properties = entityType.GetProperties();
            foreach (var prop in properties)
            {
                table.Columns.Add(prop.Name, prop.PropertyType);
            }
            return table;
        }

        /// <summary>
        /// Inicializa as propriedades de classe do mesmo namespace ainda nulas com novas instâncias.
        /// </summary>
        public static void InitNullComposition(object sourceObj)
        {
            if (sourceObj != null)
            {
                var classType = sourceObj.GetType();

                var classChildProps = ClassChildPropsCache.GetOrAdd(classType, t =>
                    t.GetProperties().Where(prp => prp.PropertyType.IsClass
                                          && prp.PropertyType.Namespace.Equals(classType.Namespace)).ToArray());

                if (classChildProps != null)
                {
                    foreach (var prp in classChildProps)
                        if (prp.GetValue(sourceObj, null) == null)
                            prp.SetValue(sourceObj, Activator.CreateInstance(prp.PropertyType), null);
                }
            }
        }

        /// <summary>
        /// Copia os valores das propriedades de um objeto para outro.
        /// </summary>
        public static void CloneObjectData(object source, object destination)
        {
            if (source != null)
            {
                var sourceType = source.GetType();

                foreach (var prp in GetObjectProps(source))
                    if (prp.CanWrite)
                    {
                        if ((destination == null) && (sourceType.IsClass))
                            destination = Activator.CreateInstance(sourceType);

                        var destProp = GetObjectProps(destination, prp.Name);

                        if (destProp.Length > 0)
                        {
                            if (!prp.PropertyType.Namespace.Equals(source.GetType().Namespace))
                            {
                                if (prp.PropertyType.Name.Equals("List`1"))
                                {
                                    var srcListInstance = (IList)prp.GetValue(source, null);
                                    var dstListInstance = (IList)destProp[0].GetValue(destination, null);

                                    if ((srcListInstance != null) && (dstListInstance != null))
                                        foreach (var listItem in srcListInstance)
                                        {
                                            object destItem = Activator.CreateInstance(listItem.GetType());
                                            CloneObjectData(listItem, destItem);
                                            ((IList)dstListInstance).Add(destItem);
                                        }
                                }
                                else
                                    GetObjectProps(destination, prp.Name)[0].SetValue(destination,
                                                                prp.GetValue(source, null), null);
                            }
                            else
                                CloneObjectData(prp.GetValue(source, null),
                                                GetObjectProps(destination, prp.Name)[0]
                                                .GetValue(destination, null));
                        }
                        else
                        {
                            var sourceTypeName = source.GetType().Name;
                            if (sourceTypeName.StartsWith("DynamicClass") || sourceTypeName.Equals("JObject"))
                                foreach (var child in getObjectChilds(destination))
                                    CloneObjectData(source, child);
                        }
                    }
            }
        }

        /// <summary>
        /// Obtém as propriedades de um objeto, opcionalmente filtrando por nomes ou caminhos compostos.
        /// </summary>
        public static PropertyInfo[] GetObjectProps(object source, params object[] filter)
        {
            List<PropertyInfo> result = new List<PropertyInfo>();

            if (source != null)
            {
                var objProps = TypePropsCache.GetOrAdd(source.GetType(), t => t.GetProperties());

                if (filter.Length > 0)
                    foreach (var flt in filter)
                        if (!flt.ToString().Contains("."))
                        {
                            foreach (var prp in objProps)
                                if (prp.Name.Equals(flt.ToString()))
                                    result.Add(prp);
                        }
                        else
                        {
                            var child = flt.ToString().Split('.');
                            var childSource = source.GetType().GetProperty(child[0]);
                            var childInstance = childSource.GetValue(source, null);
                            if (childInstance == null)
                                childInstance = Activator.CreateInstance(childSource.PropertyType);
                            var childProp = childInstance.GetType().GetProperty(child[1]);
                            if (childProp != null) result.Add(childProp);
                        }
                else
                {
                    foreach (var prp in objProps)
                        result.Add(prp);
                }
            }

            return result.ToArray();
        }

        /// <summary>
        /// Obtém os valores das propriedades indicadas para uma instância.
        /// </summary>
        public static object[] GetObjectPropValues(object source, PropertyInfo[] properties)
        {
            List<object> result = new List<object>();

            if (properties != null)
                foreach (var prp in properties)
                    result.Add(prp.GetValue(source, null));

            return result.ToArray();
        }

        /// <summary>
        /// Converte um valor bruto (DBNull/string) para o tipo indicado.
        /// </summary>
        public static object GetTypedValue(Type propType, object propValue)
        {
            object typedValue = null;

            if (propValue != null)
                if (propValue.GetType().FullName.Contains("DBNull")
                         || propValue.GetType().FullName.Contains("Null"))
                    typedValue = null;
                else
                {
                    var converter = TypeValueConvertersCache.GetOrAdd(propType, t =>
                    {
                        Func<object, object> convert;

                        if (t.FullName.Contains("Int16"))
                            convert = v => (object)short.Parse(v.ToString());
                        else if (t.FullName.Contains("Int32"))
                            convert = v => (object)int.Parse(v.ToString());
                        else if (t.FullName.Contains("Int64"))
                            convert = v => (object)long.Parse(v.ToString());
                        else if (t.FullName.Contains("Decimal"))
                            convert = v => (object)decimal.Parse(v.ToString());
                        else if (t.FullName.Contains("Double"))
                            convert = v => (object)double.Parse(v.ToString());
                        else if (t.FullName.Contains("Float"))
                            convert = v => (object)float.Parse(v.ToString());
                        else if (t.FullName.Contains("Single"))
                            convert = v => (object)Single.Parse(v.ToString());
                        else if (t.FullName.Contains("Short"))
                            convert = v => (object)short.Parse(v.ToString());
                        else if (t.FullName.Contains("Boolean"))
                            convert = v => (object)bool.Parse(v.ToString());
                        else if (t.FullName.Contains("String"))
                            convert = v => v.ToString();
                        else if (t.FullName.Contains("DateTime"))
                            convert = v => (object)DateTime.Parse(v.ToString());
                        else
                            convert = v => v;

                        return convert;
                    });

                    typedValue = converter(propValue);
                }

            return typedValue;
        }

        /// <summary>
        /// Obtém as instâncias das classes filho de um objeto.
        /// </summary>
        internal static object[] getObjectChilds(object destination)
        {
            var childProps = ClassChildPropsCache.GetOrAdd(destination.GetType(), t =>
                t.GetProperties().Where(prp => prp.PropertyType.Namespace.Equals(t.Namespace)).ToArray());

            var result = new List<object>();
            foreach (var child in childProps)
                result.Add(child.GetValue(destination, null));

            return result.ToArray();
        }

        /// <summary>
        /// Cria uma nova instância de T copiando os valores das propriedades da origem.
        /// </summary>
        public static T CloneObjectData<T>(object source)
        {
            T destination = Activator.CreateInstance<T>();

            foreach (var prp in GetObjectProps(source))
                GetObjectProps(destination, prp.Name)[0].SetValue(destination,
                                                           prp.GetValue(source, null), null);

            return destination;
        }
    }
}